<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Posit.Tools</RootNamespace>
    <AssemblyName>Posit.Tools</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Posit.Contracts\Posit.Contracts.csproj" />
    <ProjectReference Include="..\Posit.Data\Posit.Data.csproj" />
    <ProjectReference Include="..\Posit.AI\Posit.AI.csproj" />
  </ItemGroup>

</Project>