<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Dafny</RootNamespace>
    <AssemblyName>Posit.DafnyRuntime</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="DafnyRuntime.dll">
      <HintPath>DafnyRuntime.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>