namespace Posit.Contracts.Artifacts;

/// <summary>
/// Test suite artifact produced by the QA phase. Contains test files
/// for the CLI component and expected output maps for exact comparison.
/// </summary>
public record TestSuite
{
    public SourceCodeFile[] TestFiles { get; init; } = [];
    public required string Summary { get; init; }
    /// <summary>
    /// Expected output per test case, keyed by test case ID (e.g. "tc1", "tc2").
    /// Empty = no exact match available (structural/heuristic comparison).
    /// </summary>
    public Dictionary<string, string> ExpectedOutputs { get; init; } = [];
    /// <summary>
    /// Expected exit code per test case, keyed by test case ID.
    /// </summary>
    public Dictionary<string, int> ExpectedExitCodes { get; init; } = [];
}

/// <summary>
/// A single test data file generated by the pseudodata bot or fallback.
/// </summary>
public record TestDataFile
{
    public string FileName { get; init; } = "";
    public string Content { get; init; } = "";
    public string Description { get; init; } = "";
    /// <summary>
    /// The exact stdout output expected when the program processes this test input.
    /// Empty string = no exact match (structural/heuristic comparison).
    /// </summary>
    public string ExpectedOutput { get; init; } = "";
    /// <summary>
    /// Expected exit code. 0 = success, 1 = error. Default 0.
    /// </summary>
    public int ExpectedExitCode { get; init; } = 0;
}