// Variant 11: aggregator (operation=CountPositive, collectionType=seq<bool>)
// Generated by parameter substitution

// Pattern: Aggregator (Approach 3 — pre-written body with parameters)
// responsibility: Fold/reduce over a collection to produce a summary value
// test: Sum([1, 2, 3, 4, 5]) returns 15
// test: Max([3, 7, 2, 9, 1]) returns 9
// test: Count([true, false, true, true]) returns 3
//
// Parameters:
//   operation: the fold operation (Sum, Max, Min, Count, Average)
//   initialValue: the starting accumulator value

// Sum of a sequence of integers
method Sum(values: seq<int>) returns (total: int)
  requires |values| > 0
  ensures total == SumSeq(values)
  decreases |values|
{
  total := SumSeq(values);
}

// Maximum value in a sequence
method Max(values: seq<int>) returns (maxVal: int)
  requires |values| > 0
  ensures maxVal == MaxSeq(values)
  decreases |values|
{
  maxVal := MaxSeq(values);
}

// Count elements satisfying a predicate (count of positive numbers)
method CountPositive(values: seq<int>) returns (count: int)
  ensures count >= 0
  ensures count <= |values|
  decreases |values|
{
  count := 0;
  var i := 0;
  while i < |values|
    invariant 0 <= i <= |values|
    invariant count <= i
    decreases |values| - i
  {
    if values[i] > 0 {
      count := count + 1;
    }
    i := i + 1;
  }
}

// Helper: sum of a sequence (used in postcondition)
function SumSeq(values: seq<int>): int
  decreases |values|
{
  if |values| == 0 then 0
  else values[0] + SumSeq(values[1..])
}

// Helper: max of a non-empty sequence
function MaxSeq(values: seq<int>): int
  requires |values| > 0
  decreases |values|
{
  if |values| == 1 then values[0]
  else if values[0] >= MaxSeq(values[1..]) then values[0]
  else MaxSeq(values[1..])
}