// Variant 7: builder (separator=, , validateEmpty=false, feature=withSuffix)
// Generated by parameter substitution

// Pattern: Builder (Approach 3 — pre-written body with parameters)
// responsibility: Accumulate parts, build with invariants on the final result
// test: Join(["a", "b", "c"], ",") returns "a,b,c"
// test: Join(["hello"], ",") returns "hello"
// test: Join([], ",") returns ""
//
// Parameters:
//   separator: string — what to join parts with (default ",")
//   prefix: string — optional prefix for the result (default "")
//   suffix: string — optional suffix for the result (default "")

// Join a sequence of strings with a separator
method Join(parts: seq<string>, separator: string) returns (result: string)
  ensures |result| >= 0
  decreases |parts|
{
  if |parts| == 0 {
    result := "";
  } else if |parts| == 1 {
    result := parts[0];
  } else {
    result := parts[0];
    var i := 1;
    while i < |parts|
      invariant 1 <= i <= |parts|
      decreases |parts| - i
    {
      result := result + separator + parts[i];
      i := i + 1;
    }
  }
}

// Build with prefix and suffix
method Build(parts: seq<string>, separator: string, prefix: string, suffix: string) returns (result: string)
  requires |parts| > 0
  ensures |result| >= |prefix| + |suffix|
  decreases |parts|
{
  var joined := Join(parts, separator);
  result := prefix + joined + suffix;
}

// Accumulate parts into a string with separator, skipping empty parts
method JoinNonEmpty(parts: seq<string>, separator: string) returns (result: string)
  ensures |result| >= 0
  decreases |parts|
{
  result := "";
  var first := true;
  var i := 0;
  while i < |parts|
    invariant 0 <= i <= |parts|
    decreases |parts| - i
  {
    if |parts[i]| > 0 {
      if !first {
        result := result + separator;
      }
      result := result + parts[i];
      first := false;
    }
    i := i + 1;
  }
}