// Variant 0: filter (predicate=even, feature=basic)
// Generated by parameter substitution

// Pattern: Filter (Approach 3 — pre-written body with parameters)
// responsibility: Predicate-based collection filtering
// test: FilterPositive([1, -2, 3, -4, 5]) returns [1, 3, 5]
// test: FilterPositive([]) returns []
// test: FilterPositive([-1, -2, -3]) returns []
// test: FilterLongerThan(["a", "bb", "ccc", "dd"], 1) returns ["bb", "ccc", "dd"]
//
// Parameters:
//   predicate: the filtering condition (customized per domain)
//   keepEmpty: bool — whether to preserve empty input or return empty (default false)

// Filter: keep elements greater than zero
method FilterPositive(values: seq<int>) returns (result: seq<int>)
  ensures |result| <= |values|
  ensures forall i :: 0 <= i < |result| ==> result[i] > 0
  decreases |values|
{
  result := [];
  var i := 0;
  while i < |values|
    invariant 0 <= i <= |values|
    invariant |result| <= i
    invariant forall j :: 0 <= j < |result| ==> result[j] > 0
    decreases |values| - i
  {
    if values[i] > 0 {
      result := result + [values[i]];
    }
    i := i + 1;
  }
}

// Filter: keep strings longer than minLength
method FilterLongerThan(strings: seq<string>, minLength: int) returns (result: seq<string>)
  requires minLength >= 0
  ensures |result| <= |strings|
  ensures forall i :: 0 <= i < |result| ==> |result[i]| > minLength
  decreases |strings|
{
  result := [];
  var i := 0;
  while i < |strings|
    invariant 0 <= i <= |strings|
    invariant |result| <= i
    invariant forall j :: 0 <= j < |result| ==> |result[j]| > minLength
    decreases |strings| - i
  {
    if |strings[i]| > minLength {
      result := result + [strings[i]];
    }
    i := i + 1;
  }
}

// Filter: keep elements in a range [low, high]
method FilterInRange(values: seq<int>, low: int, high: int) returns (result: seq<int>)
  requires low <= high
  ensures |result| <= |values|
  ensures forall i :: 0 <= i < |result| ==> low <= result[i] <= high
  decreases |values|
{
  result := [];
  var i := 0;
  while i < |values|
    invariant 0 <= i <= |values|
    invariant |result| <= i
    invariant forall j :: 0 <= j < |result| ==> low <= result[j] <= high
    decreases |values| - i
  {
    if values[i] >= low && values[i] <= high {
      result := result + [values[i]];
    }
    i := i + 1;
  }
}

// Filter: keep non-empty strings
method FilterNonEmpty(strings: seq<string>) returns (result: seq<string>)
  ensures |result| <= |strings|
  ensures forall i :: 0 <= i < |result| ==> |result[i]| > 0
  decreases |strings|
{
  result := [];
  var i := 0;
  while i < |strings|
    invariant 0 <= i <= |strings|
    invariant |result| <= i
    invariant forall j :: 0 <= j < |result| ==> |result[j]| > 0
    decreases |strings| - i
  {
    if |strings[i]| > 0 {
      result := result + [strings[i]];
    }
    i := i + 1;
  }
}

// Count elements that pass a predicate (count of positive values)
method CountIfPositive(values: seq<int>) returns (count: int)
  ensures count >= 0
  ensures count <= |values|
  decreases |values|
{
  count := 0;
  var i := 0;
  while i < |values|
    invariant 0 <= i <= |values|
    invariant count <= i
    decreases |values| - i
  {
    if values[i] > 0 {
      count := count + 1;
    }
    i := i + 1;
  }
}

// Helper: count strings longer than a threshold
function CountLongerThan(strings: seq<string>, minLength: int): int
  requires minLength >= 0
  ensures 0 <= CountLongerThan(strings, minLength) <= |strings|
  decreases |strings|
{
  if |strings| == 0 then 0
  else (if |strings[0]| > minLength then 1 else 0) + CountLongerThan(strings[1..], minLength)
}