// Variant 9: graph (traversal=Dijkstra, feature=weighted)
// Generated by parameter substitution

// Pattern: Graph (Approach 3 — pre-written body with parameters)
// responsibility: Nodes, edges, traversal, and search
// test: HasEdge([[], [2], [3], []], 1, 2) returns true
// test: HasEdge([[], [2], [3], []], 2, 3) returns true
// test: HasEdge([[], [2], [3], []], 1, 3) returns false
// test: Reachable([[], [2], [3], []], 1, 3) returns true
// test: Reachable([[], [2], [3], []], 3, 1) returns false
//
// Parameters:
//   directed: bool — whether edges are directed (default true)
//   maxNodes: int — capacity hint for node allocation

include "result.dfy"

// Adjacency list: adj[node] = sequence of neighbor node IDs.
// Node IDs are integers in [0, |adj|).

// Add a new node (appends an empty neighbor list)
method AddNode(adj: seq<seq<int>>) returns (newAdj: seq<seq<int>>)
  ensures |newAdj| == |adj| + 1
  ensures newAdj[|adj|] == []
  ensures forall i :: 0 <= i < |adj| ==> newAdj[i] == adj[i]
{
  newAdj := adj + [[]];
}

// Add a directed edge from -> to
method AddEdge(adj: seq<seq<int>>, from: int, to: int) returns (newAdj: seq<seq<int>>)
  requires 0 <= from < |adj|
  requires 0 <= to < |adj|
  ensures |newAdj| == |adj|
  ensures forall i :: 0 <= i < |adj| && i != from ==> newAdj[i] == adj[i]
  ensures to in newAdj[from]
{
  newAdj := adj[..from] + [adj[from] + [to]] + adj[from + 1..];
}

// Check if an edge from -> to exists
method HasEdge(adj: seq<seq<int>>, from: int, to: int) returns (found: bool)
  requires 0 <= from < |adj|
  ensures found ==> exists k :: 0 <= k < |adj[from]| && adj[from][k] == to
{
  found := false;
  ghost var foundIdx := -1;
  var i := 0;
  while i < |adj[from]|
    invariant 0 <= i <= |adj[from]|
    invariant -1 <= foundIdx < i
    invariant found == (foundIdx >= 0)
    invariant foundIdx >= 0 ==> adj[from][foundIdx] == to
    decreases |adj[from]| - i
  {
    if !found && adj[from][i] == to {
      found := true;
      foundIdx := i;
    }
    i := i + 1;
  }
}

// Helper: prove that to is in the sequence (used to establish membership)
function InSeq(s: seq<int>, to: int): bool
  decreases |s|
{
  if |s| == 0 then false
  else if s[0] == to then true
  else InSeq(s[1..], to)
}

// Get the neighbor list for a node
function GetNeighbors(adj: seq<seq<int>>, node: int): seq<int>
  requires 0 <= node < |adj|
{
  adj[node]
}

// Check if target is reachable from start (recursive DFS)
function Reachable(adj: seq<seq<int>>, start: int, target: int): bool
  requires 0 <= start < |adj|
  requires 0 <= target < |adj|
{
  ReachableDFS(adj, start, target, set i | 0 <= i < |adj|)
}

// Recursive DFS helper: explores unvisited nodes
function ReachableDFS(adj: seq<seq<int>>, start: int, target: int, unvisited: set<int>): bool
  requires 0 <= start < |adj|
  requires 0 <= target < |adj|
  requires start in unvisited
  requires forall n :: n in unvisited ==> 0 <= n < |adj|
  decreases |unvisited|, 0
{
  if start == target then true
  else ReachableViaNeighbors(adj, target, unvisited - {start}, adj[start])
}

// Iterate over neighbors, recursing into unvisited ones
function ReachableViaNeighbors(adj: seq<seq<int>>, target: int, unvisited: set<int>, neighbors: seq<int>): bool
  requires 0 <= target < |adj|
  requires forall n :: n in unvisited ==> 0 <= n < |adj|
  decreases |unvisited|, |neighbors|
{
  if |neighbors| == 0 then false
  else if 0 <= neighbors[0] < |adj| && neighbors[0] in unvisited then
    ReachableDFS(adj, neighbors[0], target, unvisited) || ReachableViaNeighbors(adj, target, unvisited, neighbors[1..])
  else
    ReachableViaNeighbors(adj, target, unvisited, neighbors[1..])
}

// Search: check reachability, returning a Result
method Search(adj: seq<seq<int>>, start: int, target: int) returns (result: Result<bool>)
  requires 0 <= start < |adj|
  requires 0 <= target < |adj|
  ensures result.Success?
  ensures result.value == Reachable(adj, start, target)
{
  result := Success(Reachable(adj, start, target));
}