// Variant 18: iterator (collectionType=seq<(int, string)>, feature=filtered)
// Generated by parameter substitution

// Pattern: Iterator (Approach 3 — pre-written body with parameters)
// responsibility: Traverse a collection with position tracking
// test: Next(AtPosition(0, "a", ["b", "c"])) returns AtPosition(1, "b", ["c"])
// test: Next(AtPosition(1, "b", [])) returns AtEnd
//
// Parameters:
//   stepSize: int — how many elements to advance per step (default 1)
//   direction: bool — true = forward, false = backward (default true)

datatype IteratorState<T> =
  | AtEnd
  | AtPosition(pos: int, value: T, remaining: seq<T>)

// Advance iterator one step forward
method Next<T>(state: IteratorState<T>) returns (next: IteratorState<T>)
  ensures next.AtEnd? || next.AtPosition?
{
  match state
  case AtEnd =>
    next := AtEnd;
  case AtPosition(pos, value, remaining) =>
    if |remaining| == 0 {
      next := AtEnd;
    } else {
      next := AtPosition(pos + 1, remaining[0], remaining[1..]);
    }
}

// Create an iterator from a sequence
method Create<T>(items: seq<T>) returns (state: IteratorState<T>)
  ensures |items| == 0 ==> state.AtEnd?
  ensures |items| > 0 ==> state.AtPosition?
{
  if |items| == 0 {
    state := AtEnd;
  } else {
    state := AtPosition(0, items[0], items[1..]);
  }
}

// Check if iterator has more elements
function HasMore<T>(state: IteratorState<T>): bool
{
  match state
  case AtEnd => false
  case AtPosition(pos, value, remaining) => true
}

// Get current value without advancing
function Current<T>(state: IteratorState<T>): T
  requires state.AtPosition?
{
  state.value
}

// Count remaining elements (including current)
function RemainingCount<T>(state: IteratorState<T>): int
  decreases state
{
  match state
  case AtEnd => 0
  case AtPosition(pos, value, remaining) => 1 + |remaining|
}