// Variant 1: reducer (actionType=Increment, feature=withUndo)
// Generated by parameter substitution

// Pattern: Reducer (Approach 3 — pre-written body with parameters)
// responsibility: Apply an action to state with undo support
// test: Apply(0, Increment) returns 1
// test: Undo(1, Increment) returns 0
// test: ApplyN(0, [Increment, Increment, Increment]) returns 3
// test: UndoN(3, [Increment, Increment, Increment]) returns 0
//
// Parameters:
//   actions: the datatype variants (customized per domain)
//   applyLogic: how each action transforms state (the Apply body)
//   undoLogic: how each action reverses state (the Undo body)

datatype Action =
  | Increment
  | Decrement
  | SetValue(value: int)

// Apply a single action to a state, returning the new state
method Apply(state: int, action: Action) returns (result: int)
  ensures result >= 0 || result < 0
{
  if action.Increment? {
    result := state + 1;
  } else if action.Decrement? {
    result := state - 1;
  } else if action.SetValue? {
    result := action.value;
  } else {
    result := state;
  }
}

// Undo a single action: reverses the effect of Apply
method Undo(state: int, action: Action) returns (result: int)
  ensures action.Increment? ==> result == state - 1
  ensures action.Decrement? ==> result == state + 1
  ensures action.SetValue? ==> result == state
{
  if action.Increment? {
    result := state - 1;
  } else if action.Decrement? {
    result := state + 1;
  } else if action.SetValue? {
    result := state;
  } else {
    result := state;
  }
}

// Apply a sequence of actions in order, accumulating the state
method ApplyN(initial: int, actions: seq<Action>) returns (finalState: int)
  decreases |actions|
{
  finalState := initial;
  var i := 0;
  while i < |actions|
    invariant 0 <= i <= |actions|
    decreases |actions| - i
  {
    finalState := Apply(finalState, actions[i]);
    i := i + 1;
  }
}

// Undo a sequence of actions in reverse order
method UndoN(state: int, actions: seq<Action>) returns (result: int)
  decreases |actions|
{
  result := state;
  var i := |actions| - 1;
  while i >= 0
    invariant -1 <= i < |actions|
    decreases i + 1
  {
    result := Undo(result, actions[i]);
    i := i - 1;
  }
}

// Helper: reverse a sequence of actions
function ReverseActions(actions: seq<Action>): seq<Action>
  ensures |ReverseActions(actions)| == |actions|
  decreases |actions|
{
  if |actions| == 0 then []
  else ReverseActions(actions[1..]) + [actions[0]]
}

// Count how many Increment actions are in a sequence
method CountIncrements(actions: seq<Action>) returns (count: int)
  ensures count >= 0
  ensures count <= |actions|
  decreases |actions|
{
  count := 0;
  var i := 0;
  while i < |actions|
    invariant 0 <= i <= |actions|
    invariant count <= i
    decreases |actions| - i
  {
    if actions[i].Increment? {
      count := count + 1;
    }
    i := i + 1;
  }
}