// Variant 7: strategy (algorithm=MergeSort, feature=withComparator)
// Generated by parameter substitution

// Pattern: Strategy (Approach 3 — pre-written body with parameters)
// responsibility: Interchangeable algorithms behind one interface
// test: Execute(SortAsc, [3, 1, 2]) returns [1, 2, 3]
// test: Execute(SortDesc, [3, 1, 2]) returns [3, 2, 1]
// test: Execute(Identity, [3, 1, 2]) returns [3, 1, 2]
//
// Parameters:
//   defaultStrategy: Strategy — which algorithm to use when none specified
//   maxInputSize: int — cap on input length (default 10000)
//
// Pre-cut planks: the strategy dispatch, sort implementations, and
// composition are all pre-written and Z3-proven. The architect sets the
// parameters. Imp's job is empty or near-empty.

// A strategy tag selects which algorithm to run.
datatype Strategy =
  | SortAsc
  | SortDesc
  | IdentityStrat
  | DoubleStrat

// Execute the named strategy on an input sequence, returning the result.
method Execute(strat: Strategy, input: seq<int>) returns (output: seq<int>)
  ensures |output| == |input|
  decreases |input|
{
  match strat
  case SortAsc =>
    output := InsertionSort(input);
  case SortDesc =>
    output := InsertionSortDesc(input);
  case IdentityStrat =>
    output := input;
  case DoubleStrat =>
    output := DoubleAll(input);
}

// Execute with a fallback if the primary strategy produces empty output
// (here, always uses primary since all strategies preserve length).
method ExecuteWithFallback(strat: Strategy, fallback: Strategy, input: seq<int>) returns (output: seq<int>)
  requires |input| > 0
  ensures |output| == |input|
  decreases |input|
{
  var primary := Execute(strat, input);
  if |primary| == |input| {
    output := primary;
  } else {
    output := Execute(fallback, input);
  }
}

// Compose two strategies: apply s1 first, then s2 to the result.
method Compose(s1: Strategy, s2: Strategy, input: seq<int>) returns (output: seq<int>)
  ensures |output| == |input|
  decreases |input|
{
  var intermediate := Execute(s1, input);
  output := Execute(s2, intermediate);
}

// Insertion sort ascending.
method InsertionSort(input: seq<int>) returns (sorted: seq<int>)
  ensures |sorted| == |input|
  decreases |input|
{
  sorted := [];
  var i := 0;
  while i < |input|
    invariant 0 <= i <= |input|
    invariant |sorted| == i
    decreases |input| - i
  {
    sorted := InsertOne(sorted, input[i]);
    i := i + 1;
  }
}

// Insertion sort descending.
method InsertionSortDesc(input: seq<int>) returns (sorted: seq<int>)
  ensures |sorted| == |input|
  decreases |input|
{
  sorted := [];
  var i := 0;
  while i < |input|
    invariant 0 <= i <= |input|
    invariant |sorted| == i
    decreases |input| - i
  {
    sorted := InsertOneDesc(sorted, input[i]);
    i := i + 1;
  }
}

// Insert a value into a sorted (ascending) sequence at the correct position.
function InsertOne(sorted: seq<int>, val: int): seq<int>
  ensures |InsertOne(sorted, val)| == |sorted| + 1
  decreases |sorted|
{
  if |sorted| == 0 then [val]
  else if val <= sorted[0] then [val] + sorted
  else [sorted[0]] + InsertOne(sorted[1..], val)
}

// Insert a value into a sorted (descending) sequence at the correct position.
function InsertOneDesc(sorted: seq<int>, val: int): seq<int>
  ensures |InsertOneDesc(sorted, val)| == |sorted| + 1
  decreases |sorted|
{
  if |sorted| == 0 then [val]
  else if val >= sorted[0] then [val] + sorted
  else [sorted[0]] + InsertOneDesc(sorted[1..], val)
}

// Double every element in a sequence.
method DoubleAll(input: seq<int>) returns (output: seq<int>)
  ensures |output| == |input|
  decreases |input|
{
  output := [];
  var i := 0;
  while i < |input|
    invariant 0 <= i <= |input|
    invariant |output| == i
    decreases |input| - i
  {
    output := output + [input[i] * 2];
    i := i + 1;
  }
}