// Variant 6: transformer (operation=Filter)
// Generated by parameter substitution

// Pattern: Transformer (Approach 3 — pre-written body with parameters)
// responsibility: Transform input through stages to output
// test: ToUpper(["hello", "world"]) returns ["HELLO", "WORLD"]
// test: Trim([" a ", " b "]) returns ["a", "b"]
//
// Parameters:
//   operation: the transformation applied per element (ToUpper, ToLower, Trim, etc.)
//   filterEmpty: bool — whether to drop empty results (default false)

// Apply a transformation to each element of a sequence
method TransformAll(input: seq<string>) returns (output: seq<string>)
  requires |input| > 0
  ensures |output| == |input|
  decreases |input|
{
  output := [];
  var i := 0;
  while i < |input|
    invariant 0 <= i <= |input|
    invariant |output| == i
    decreases |input| - i
  {
    output := output + [ToUpper(input[i])];
    i := i + 1;
  }
}

// Transform and filter out empty results
method TransformAndFilter(input: seq<string>) returns (output: seq<string>)
  requires |input| > 0
  ensures |output| >= 0
  ensures |output| <= |input|
  decreases |input|
{
  output := [];
  var i := 0;
  while i < |input|
    invariant 0 <= i <= |input|
    invariant |output| <= i
    decreases |input| - i
  {
    var transformed := ToUpper(input[i]);
    if |transformed| > 0 {
      output := output + [transformed];
    }
    i := i + 1;
  }
}

// Convert string to uppercase
function ToUpper(s: string): string
  decreases |s|
{
  if |s| == 0 then ""
  else if 'a' <= s[0] && s[0] <= 'z' then [CharToUpper(s[0])] + ToUpper(s[1..])
  else [s[0]] + ToUpper(s[1..])
}

// Convert lowercase char to uppercase
function CharToUpper(c: char): char
  ensures 'a' <= c <= 'z' ==> 'A' <= CharToUpper(c) <= 'Z'
{
  match c
  case 'a' => 'A'
  case 'b' => 'B'
  case 'c' => 'C'
  case 'd' => 'D'
  case 'e' => 'E'
  case 'f' => 'F'
  case 'g' => 'G'
  case 'h' => 'H'
  case 'i' => 'I'
  case 'j' => 'J'
  case 'k' => 'K'
  case 'l' => 'L'
  case 'm' => 'M'
  case 'n' => 'N'
  case 'o' => 'O'
  case 'p' => 'P'
  case 'q' => 'Q'
  case 'r' => 'R'
  case 's' => 'S'
  case 't' => 'T'
  case 'u' => 'U'
  case 'v' => 'V'
  case 'w' => 'W'
  case 'x' => 'X'
  case 'y' => 'Y'
  case 'z' => 'Z'
  case _ => c
}

// Reverse a string
function Reverse(s: string): string
  ensures |Reverse(s)| == |s|
  decreases |s|
{
  if |s| == 0 then ""
  else Reverse(s[1..]) + [s[0]]
}