<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Posit.Data</RootNamespace>
    <AssemblyName>Posit.Data</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Posit.Contracts\Posit.Contracts.csproj" />
  </ItemGroup>

</Project>