#!/usr/bin/env python3
"""
Registry indexer — scans verified .dfy variant files and populates the
posit_registry.variants table with structured data + vector embeddings.

Usage:
    python scripts/index-registry.py                    # index batch-variants/
    python scripts/index-registry.py --dir .posit/staging/variants  # custom dir
    python scripts/index-registry.py --rebuild          # drop and reindex all
"""

import json
import os
import re
import subprocess
import sys
import time
import urllib.request
import argparse
from pathlib import Path
from datetime import datetime, timezone

POSIT_ROOT = Path(__file__).parent.parent
DAFNY = "C:/Users/goldf/.dotnet/tools/dafny.exe"
Z3 = "C:/Users/goldf/.dotnet/tools/z3/bin/z3.exe"
OLLAMA_URL = "http://localhost:11434/api/embeddings"
EMBED_MODEL = "nomic-embed-text"

DB_HOST = "localhost"
DB_PORT = "5434"
DB_USER = "shepherd"
DB_NAME = "shepherd"

# ─── Helpers ──────────────────────────────────────────────────────────────

def get_embedding(text: str) -> list[float]:
    """Get embedding from Ollama."""
    data = json.dumps({"model": EMBED_MODEL, "prompt": text}).encode()
    req = urllib.request.Request(OLLAMA_URL, data=data)
    try:
        resp = urllib.request.urlopen(req, timeout=30)
        result = json.loads(resp.read())
        return result.get("embedding", [])
    except Exception as e:
        print(f"  [warn] embedding failed: {e}")
        return []


def verify_dafny(dafny_path: str) -> tuple[bool, int, str]:
    """Run dafny verify, return (success, vc_count, output)."""
    try:
        result = subprocess.run(
            [DAFNY, "verify", dafny_path,
             "--solver-path", Z3,
             "--standard-libraries", "--allow-warnings"],
            capture_output=True, text=True, timeout=120
        )
        output = result.stdout + result.stderr
        verified = result.returncode == 0 and "Error" not in output
        # Count verification conditions
        vc_match = re.search(r'(\d+) verified', output)
        vc_count = int(vc_match.group(1)) if vc_match else 0
        return verified, vc_count, output
    except Exception as e:
        return False, 0, str(e)


def verify_batch_parallel(file_paths: list, workers: int = 6) -> dict:
    """Verify multiple Dafny files in parallel. Returns {path: (success, vc_count, output)}."""
    from concurrent.futures import ProcessPoolExecutor, as_completed
    results = {}
    with ProcessPoolExecutor(max_workers=workers) as executor:
        futures = {executor.submit(verify_dafny, str(f)): str(f) for f in file_paths}
        for future in as_completed(futures):
            path = futures[future]
            try:
                results[path] = future.result()
            except Exception as e:
                results[path] = (False, 0, str(e))
    return results


def parse_variant_metadata(file_path: Path) -> dict:
    """Extract pattern name and params from variant file header."""
    content = file_path.read_text()
    
    # Parse header comments: "// Variant 0: parser (delimiter=,, quoteChar=none)"
    # or "// v001: delimiter hardcoded to |"
    lines = content.split('\n')
    pattern = "unknown"
    params = {}
    description = ""
    
    for line in lines[:5]:
        # Try "Variant N: pattern (k=v, k=v)"
        m = re.match(r'//\s*Variant\s+\d+:\s*(\w+)\s*\((.*)\)', line)
        if m:
            pattern = m.group(1)
            param_str = m.group(2)
            for pair in param_str.split(', '):
                if '=' in pair:
                    k, v = pair.split('=', 1)
                    params[k.strip()] = v.strip()
            continue
        
        # Try "v001: description"
        m = re.match(r'//\s*v\d+:\s*(.*)', line)
        if m:
            description = m.group(1).strip()
            # Try to infer pattern from filename
            pattern = file_path.stem.split('-')[0]
            continue
        
        # Try "Generated by parameter substitution"
        m = re.match(r'//\s*Variant\s+\d+:\s*(\w+)\s*\((.*)\)', line)
        if m:
            pattern = m.group(1)
    
    # Infer pattern from filename if still unknown
    if pattern == "unknown":
        name = file_path.stem
        for p in ["parser", "validator", "repository", "state-machine", "transformer",
                   "aggregator", "builder", "iterator", "result", "frames"]:
            if name.startswith(p):
                pattern = p
                break
    
    # If no description, build one from pattern + params
    if not description:
        param_str = ", ".join(f"{k}={v}" for k, v in params.items())
        description = f"{pattern} variant ({param_str})" if param_str else f"{pattern} variant"
    
    return {
        "id": file_path.stem,  # e.g., "parser-v000"
        "pattern": pattern,
        "params": params,
        "description": description,
        "source_path": str(file_path),
    }


def check_carapace(file_path: Path) -> tuple[bool, str]:
    """Check carapace limits: 200-line cap, 10-method cap, 5-class cap per module.
    Returns (passes, reason)."""
    content = file_path.read_text()
    lines = content.split('\n')
    line_count = len(lines)
    
    # Count methods (method declarations, not in comments)
    method_count = sum(1 for l in lines if re.match(r'\s*(method|function|lemma)\s', l) and not l.strip().startswith('//'))
    
    # Count class declarations
    class_count = sum(1 for l in lines if re.match(r'\s*class\s', l) and not l.strip().startswith('//'))
    
    if line_count > 200:
        return False, f"line cap exceeded: {line_count} > 200"
    if method_count > 10:
        return False, f"method cap exceeded: {method_count} > 10"
    if class_count > 5:
        return False, f"class cap exceeded: {class_count} > 5"
    
    return True, f"lines={line_count}, methods={method_count}, classes={class_count}"


def db_connect():
    """Connect to Postgres."""
    import psycopg2
    return psycopg2.connect(
        host=DB_HOST, port=DB_PORT,
        user=DB_USER, dbname=DB_NAME,
        password="shepherd"
    )


def upsert_variant(conn, variant: dict, verified: bool, vc_count: int, tokens: int, embedding: list[float]):
    """Insert or update a variant in the DB."""
    with conn.cursor() as cur:
        cur.execute("""
            INSERT INTO posit_registry.variants 
                (id, pattern, params, description, source_path, verified, vc_count, tokens, embedding, priority)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (id) DO UPDATE SET
                pattern = EXCLUDED.pattern,
                params = EXCLUDED.params,
                description = EXCLUDED.description,
                source_path = EXCLUDED.source_path,
                verified = EXCLUDED.verified,
                vc_count = EXCLUDED.vc_count,
                tokens = EXCLUDED.tokens,
                embedding = EXCLUDED.embedding,
                priority = EXCLUDED.priority,
                created_at = now()
        """, (
            variant["id"],
            variant["pattern"],
            json.dumps(variant["params"]),
            variant["description"],
            variant["source_path"],
            verified,
            vc_count,
            tokens,
            embedding if embedding else None,
            0
        ))
    conn.commit()


def search_variants(conn, query: str, limit: int = 5):
    """Search variants by semantic similarity."""
    embedding = get_embedding(query)
    if not embedding:
        return []
    
    with conn.cursor() as cur:
        cur.execute("""
            SELECT id, pattern, description, params, verified, 
                   1 - (embedding <-> %s::vector) as similarity
            FROM posit_registry.variants
            WHERE embedding IS NOT NULL AND verified = true
            ORDER BY embedding <-> %s::vector
            LIMIT %s
        """, (json.dumps(embedding), json.dumps(embedding), limit))
        
        return cur.fetchall()


# ─── Main ─────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Index verified Dafny variants into registry DB")
    parser.add_argument("--dir", type=str, default=".posit/staging/batch-variants",
                        help="Directory containing .dfy variant files")
    parser.add_argument("--rebuild", action="store_true",
                        help="Drop and reindex all variants")
    parser.add_argument("--search", type=str,
                        help="Search variants by description (no indexing)")
    parser.add_argument("--list", action="store_true",
                        help="List all variants in the DB")
    parser.add_argument("--no-verify", action="store_true",
                        help="Skip Z3 verification (trust existing status)")
    args = parser.parse_args()
    
    # Search mode
    if args.search:
        conn = db_connect()
        results = search_variants(conn, args.search)
        print(f"\nSearch: '{args.search}' — {len(results)} results")
        for r in results:
            print(f"  {r[0]}: {r[1]} — {r[2]} (similarity: {r[5]:.2f})")
        conn.close()
        return
    
    # List mode
    if args.list:
        conn = db_connect()
        with conn.cursor() as cur:
            cur.execute("""
                SELECT pattern, count(*), count(*) FILTER (WHERE verified), 
                       count(*) FILTER (WHERE embedding IS NOT NULL)
                FROM posit_registry.variants
                GROUP BY pattern
                ORDER BY pattern
            """)
            print(f"\n{'pattern':<20} {'total':>6} {'verified':>9} {'embedded':>9}")
            print("-" * 48)
            for r in cur.fetchall():
                print(f"{r[0]:<20} {r[1]:>6} {r[2]:>9} {r[3]:>9}")
            cur.execute("SELECT count(*) FROM posit_registry.variants")
            total = cur.fetchone()[0]
            print(f"\nTotal: {total} variants")
        conn.close()
        return
    
    # Index mode
    variant_dir = POSIT_ROOT / args.dir
    if not variant_dir.exists():
        print(f"[skip] Directory not found: {variant_dir}")
        return
    
    dfy_files = sorted(variant_dir.glob("*.dfy"))
    if not dfy_files:
        print(f"[skip] No .dfy files in {variant_dir}")
        return
    
    print(f"\n{'='*60}")
    print(f"Indexing {len(dfy_files)} variant files from {variant_dir}")
    print(f"{'='*60}")
    
    conn = db_connect()
    
    if args.rebuild:
        with conn.cursor() as cur:
            cur.execute("TRUNCATE posit_registry.variants")
        conn.commit()
        print("[rebuild] Table truncated")
    
    indexed = 0
    verified_count = 0
    embedded_count = 0
    dedup_count = 0
    carapace_fail_count = 0
    seen_hashes = set()
    
    # Phase 1: carapace + dedup filter (fast, no Z3)
    candidates = []
    for i, dfy_file in enumerate(dfy_files):
        variant = parse_variant_metadata(dfy_file)
        
        # Check carapace limits (200-line, 10-method, 5-class caps)
        carapace_ok, carapace_msg = check_carapace(dfy_file)
        if not carapace_ok:
            carapace_fail_count += 1
            continue
        
        # Dedup: hash the code (minus header comments) and skip if already seen
        content = dfy_file.read_text()
        code_lines = [l for l in content.split('\n') if not l.startswith('// Variant') and not l.startswith('// Generated')]
        code_hash = hash(''.join(code_lines).strip())
        if code_hash in seen_hashes:
            dedup_count += 1
            continue
        seen_hashes.add(code_hash)
        
        candidates.append((dfy_file, variant))
    
    print(f"\n  Filter: {len(dfy_files)} files → {len(candidates)} candidates (carapace fail: {carapace_fail_count}, dedup: {dedup_count})")
    
    # Phase 2: Z3 verification in parallel (6 workers)
    if args.no_verify:
        z3_results = {str(f): (True, 0, "") for f, v in candidates}
    else:
        print(f"  Z3 verifying {len(candidates)} files with 6 parallel workers...")
        z3_results = verify_batch_parallel([f for f, v in candidates], workers=6)
    
    # Phase 3: embed + index
    for i, (dfy_file, variant) in enumerate(candidates):
        verified, vc_count, _ = z3_results.get(str(dfy_file), (False, 0, ""))
        
        if verified:
            verified_count += 1
        
        # Generate embedding
        embed_text = f"{variant['pattern']} {variant['description']} {json.dumps(variant['params'])}"
        embedding = get_embedding(embed_text)
        if embedding:
            embedded_count += 1
        
        # Upsert into DB
        upsert_variant(conn, variant, verified, vc_count, 0, embedding)
        indexed += 1
        
        status = "✅" if verified else "❌"
        emb = "📝" if embedding else "  "
        print(f"  [{i+1}/{len(dfy_files)}] {variant['id']:20s} {status} {emb} {variant['description'][:60]}")
    
    print(f"\n{'='*60}")
    print(f"SUMMARY")
    print(f"  Indexed: {indexed}")
    print(f"  Verified: {verified_count}/{indexed}")
    print(f"  Embedded: {embedded_count}/{indexed}")
    print(f"  Deduped:  {dedup_count} (identical code skipped)")
    print(f"{'='*60}")
    
    # Show DB stats
    with conn.cursor() as cur:
        cur.execute("""
            SELECT pattern, count(*), count(*) FILTER (WHERE verified)
            FROM posit_registry.variants
            GROUP BY pattern
            ORDER BY pattern
        """)
        print(f"\n  {'pattern':<20} {'total':>6} {'verified':>9}")
        print(f"  {'-'*38}")
        for r in cur.fetchall():
            print(f"  {r[0]:<20} {r[1]:>6} {r[2]:>9}")
    
    conn.close()
    print(f"\nDone. Use --search to query, --list to see stats.")


if __name__ == "__main__":
    main()